#!/usr/bin/env python3

import socket
import sys
from datetime import datetime

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
addr = input('Enter IP Address: ')
s.connect((addr, 1303))
data = s.recv(10)
print(data)
s.close()
