#!/usr/bin/env python3

import socket
import sys
from datetime import datetime

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind(('0.0.0.0', 1303))
s.listen()
try:
    while True:
        connection, addr = s.accept()
        time = str(datetime.now().strftime("%d.%m.%Y %H:%M"))
        connection.send(time.encode())
        connection.close()
except KeyboardInterrupt:
    sys.exit(0)
