#!/usr/bin/env python3

import socket
import sys
from datetime import datetime

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
addr = input('Enter IP Address: ')
s.bind((addr, 1303))
s.listen()
connection, addr = s.accept()
data = connection.recv(16)
print(data)
connection.close()
